DROP TABLE wines;
CREATE TABLE wines(
    id SERIAL PRIMARY KEY,
	datotid VARCHAR (255) NOT NULL,
    varenummer INT NOT NULL,
    varenavn VARCHAR (255) NOT NULL,
    volum REAL NOT NULL,
    pris REAL NOT NULL,
    literpris REAL NOT NULL,
    varetype VARCHAR (255) NOT NULL,
    produktutvalg VARCHAR (255) NOT NULL,
    butikkategori REAL NOT NULL,
    fylde REAL NOT NULL,
    friskhet REAL NOT NULL,
    garvestoffer REAL NOT NULL,
    bitterhet REAL NOT NULL,
    sodme REAL NOT NULL,
    farge VARCHAR (255) NOT NULL,
    lukt VARCHAR (255) NOT NULL,
    smak VARCHAR (255) NOT NULL,
    passertil01 VARCHAR (255) NOT NULL,
    passertil02 VARCHAR (255) NOT NULL,
    passertil03 VARCHAR (255) NOT NULL,
    land VARCHAR (255) NOT NULL,
    distrikt VARCHAR (255) NOT NULL,
    underdistrikt VARCHAR (255) NOT NULL,
    argang REAL,
    rastoff VARCHAR (255) NOT NULL,
    metode VARCHAR (255) NOT NULL,
    alkohol REAL NOT NULL,
    sukker VARCHAR (255),
    syre REAL,
    lagringsgrad VARCHAR (255) NOT NULL,
    produsent VARCHAR (255) NOT NULL,
    grossist VARCHAR (255) NOT NULL,
    distributor VARCHAR (255) NOT NULL,
    emballasjetype VARCHAR (255) NOT NULL,
    korktype VARCHAR (255) NOT NULL,
    vareurl VARCHAR (255) NOT NULL,
    okologisk BOOLEAN NOT NULL,
    biodynamisk BOOLEAN NOT NULL,
    fairtrade BOOLEAN NOT NULL,
    miljosmart_emballasje BOOLEAN NOT NULL,
    gluten_lav_pa BOOLEAN NOT NULL,
    kosher BOOLEAN NOT NULL,
    hovedgtin REAL NOT NULL,
    score REAL,
    ratings INT NOT NULL
);
