create table wines
(
	id, bigint unsigned auto_increment
	datotid, varchar(255) not null,
	varenummer, int not null,
	varenavn, varchar(255) not null,
	volum, double not null,
	pris, double not null,
	literpris, double not null,
	varetype, varchar(255) not null,
	produktutvalg, varchar(255) not null,
	butikkategori, double not null,
	fylde, double not null,
	friskhet, double not null,
	garvestoffer, double not null,
	bitterhet, double not null,
	sodme, double not null,
	farge, varchar(255) not null,
	lukt, varchar(255) not null,
	smak, varchar(255) not null,
	passertil01, varchar(255) not null,
	passertil02, varchar(255) not null,
	passertil03, varchar(255) not null,
	land, varchar(255) not null,
	distrikt, varchar(255) not null,
	underdistrikt, varchar(255) not null,
	argang, double null,
	rastoff, varchar(255) not null,
	metode, varchar(255) not null,
	alkohol, double not null,
	sukker, varchar(255) null,
	syre, double null,
	lagringsgrad, varchar(255) not null,
	produsent, varchar(255) not null,
	grossist, varchar(255) not null,
	distributor, varchar(255) not null,
	emballasjetype, varchar(255) not null,
	korktype, varchar(255) not null,
	vareurl, varchar(255) not null,
	okologisk, tinyint(1) not null,
	biodynamisk, tinyint(1) not null,
	fairtrade, tinyint(1) not null,
	miljosmart_emballasje, tinyint(1) not null,
	gluten_lav_pa, tinyint(1) not null,
	kosher, tinyint(1) not null,
	constraint wines_wine_meta_id_fk
		foreign key (meta) references wine_meta (id)
);

create unique index wines_meta_uindex
	on wines (meta);
