# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the feature/wines branch
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches: master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: yarn --frozen-lockfile

    - name: Lint Typescript
      run: yarn lint

  build_web:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Dependencies
      # TODO: Figure out why 'yarn workspace polfarer-web --frozen-lockfile' only works locally
      run: yarn --frozen-lockfile

    - name: Lint styles
      working-directory: ./web
      run: yarn stylelint

    - name: build
      working-directory: ./web
      env:
        FIREBASE_apiKey: ${{ secrets.FIREBASE_apiKey }}
        FIREBASE_authDomain: ${{ secrets.FIREBASE_authDomain }}
        FIREBASE_databaseURL: ${{ secrets.FIREBASE_databaseURL }}
        FIREBASE_projectId: ${{ secrets.FIREBASE_projectId }}
        FIREBASE_storageBucket: ${{ secrets.FIREBASE_storageBucket }}
        FIREBASE_messagingSenderId: ${{ secrets.FIREBASE_messagingSenderId }}
        FIREBASE_appId: ${{ secrets.FIREBASE_appId }}
        FIREBASE_measurementId: ${{ secrets.FIREBASE_measurementId }}
      run: |
        yarn prod

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: public
        path: web/public/


  build_functions:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Dependencies
      # TODO: Figure out why 'yarn workspace polfarer-functions --frozen-lockfile' only works locally
      run: yarn --frozen-lockfile

    - name: build
      working-directory: ./functions
      run: |
        yarn build

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: functions_lib
        path: functions/lib/

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [lint, build_functions, build_web]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Download functions artifact
      uses: actions/download-artifact@v2
      with:
        name: functions_lib
        path: ./functions/lib

    - name: Download web artifact
      uses: actions/download-artifact@v2
      with:
        name: public
        path: ./web/public

    - name: Install firebase-tools
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
      run: |
        yarn --production
        yarn firebase use $FIREBASE_PROJECTID --token "$FIREBASE_TOKEN"

    - name: Deploy secrets
      env:
        db_host: ${{ secrets.DB_host}}
        db_database: ${{ secrets.DB_database}}
        db_user: ${{ secrets.DB_user}}
        db_password: ${{ secrets.DB_password}}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        chmod +x functions/scripts/*.sh
        functions/scripts/updateSecrets.sh

    - name: Deploy services
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: | # Sed fixes node version requirements for firebase function
        sed -i -e 's/>=14/8/g' functions/package.json
        yarn firebase deploy --token "$FIREBASE_TOKEN"
